# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connexion.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(503, 465)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(50, -50, 480, 571))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.widget.setFont(font)
        self.widget.setStyleSheet("background-color:rgba(16,16,16,255);\n"
"border-radius:20px;")
        self.widget.setObjectName("widget")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(130, 130, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(70, 150, 321, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: rgba(47,49,52,200);\n"
"color: rgb(255,255,255);\n"
"border-radius:2px;\n"
"padding-left: 10px;\n"
"border: 1px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgba(46,82,101,255);\n"
"padding-bottom:3px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setGeometry(QtCore.QRect(70, 210, 321, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background-color: rgba(47,49,52,200);\n"
"color: rgb(255,255,255);\n"
"border-radius:2px;\n"
"padding-left: 10px;\n"
"border: 1px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgba(46,82,101,255);\n"
"padding-bottom:3px;")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.b1 = QtWidgets.QPushButton(self.widget)
        self.b1.setGeometry(QtCore.QRect(80, 280, 301, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.b1.setFont(font)
        self.b1.setStyleSheet("QPushButton#b1{\n"
"background-color:rgb(255,191,16);\n"
"color:rgb(135,60,0);\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton#b1:pressed{\n"
"background-color:rgb(255,255,16);\n"
"}\n"
"\n"
"\n"
"")
        self.b1.setObjectName("b1")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(170, 40, 131, 111))
        font = QtGui.QFont()
        font.setPointSize(70)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(255,191,16);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(80, 360, 311, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255,191,16);")
        self.label_2.setObjectName("label_2")
        self.b2 = QtWidgets.QPushButton(self.widget)
        self.b2.setGeometry(QtCore.QRect(200, 400, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.b2.setFont(font)
        self.b2.setStyleSheet("QPushButton#b2{\n"
"background-color:rgb(255,191,16);\n"
"color:rgb(135,60,0);\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton#b2:pressed{\n"
"background-color:rgb(255,255,16);\n"
"}")
        self.b2.setObjectName("b2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Email"))
        self.lineEdit_3.setPlaceholderText(_translate("Form", "Mot de Pass"))
        self.b1.setText(_translate("Form", "Se Connecter"))
        self.label.setText(_translate("Form", ""))
        self.label_2.setText(_translate("Form", "Vous n\'avez pas de compte ? Cliquez sur ce bouton"))
        self.b2.setText(_translate("Form", "S\'Inscrire "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
